#DATABASE
POSTGRES_HOST: localhost
POSTGRES_PORT: 5431
POSTGRES_DB: authorization_server
POSTGRES_USERNAME: admin
POSTGRES_PASSWORD: root

#Resilience
LIMIT_FOR_PERIOD: 100
LIMIT_REFRESH_PERIOD: 10m
TIMEOUT_DURATION: 0
REGISTER_HEALTH_INDICATOR: true